# Generated by Django 4.2.3 on 2023-07-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.IntegerField(max_length=60)),
                ('fecha_inicio', models.DateField()),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
    ]
